export type Mode =
  | "pan"
  | "select"
  | "move"
  | "set-waypoint"
  | "add-collider"
  | "paint"
  | "autotiler"
  | "set-bounds"
  | "set-sensor-zone"
  | "set-sound-zone"
  | "set-zoom-zone"
  | "set-sink-zone"
  | "add-light"
  | "set-gateway"
  | "duplicate";
