/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/players/{playerId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Returns the current player's information. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The ID of the player */
                    playerId: components["parameters"]["PlayerId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A player object */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Player"];
                    };
                };
                /** @description Forbidden - Player does not have access to this resource */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Player not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/players/{playerId}/inventory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Returns the current player's inventory. */
        get: {
            parameters: {
                query?: {
                    /** @description Cursor for pagination, used to fetch the next set of results */
                    cursor?: string;
                };
                header?: never;
                path: {
                    /** @description The ID of the player */
                    playerId: components["parameters"]["PlayerId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A paginated list of items in the player's inventory */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: components["schemas"]["Item"][];
                            /** @description A cursor for pagination, used to fetch the next set of results */
                            cursor?: string;
                        };
                    };
                };
                /** @description Forbidden - Player does not have access to this resource */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Player not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/levels/random": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Returns a random level. */
        get: {
            parameters: {
                query?: {
                    /** @description If provided, the random level will be selected relative to this level id */
                    from?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A random level object */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Level"];
                    };
                };
                /** @description No levels found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/levels/{levelId}/publish-jobs/{jobId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a publish job status. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The internal Github id of the level, which never changes, even if the repo is transferred. */
                    levelId: components["parameters"]["LevelId"];
                    /** @description The ID of the publish job */
                    jobId: components["parameters"]["JobId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Upload url generated successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["JobStatusResponse"];
                    };
                };
                /** @description Unauthenticated - Missing or invalid authentication token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Job not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/levels/{levelId}/upload-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate an upload URL for a level. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The internal Github id of the level, which never changes, even if the repo is transferred. */
                    levelId: components["parameters"]["LevelId"];
                };
                cookie?: never;
            };
            /** @description GitHub token from workflow job, to be forwarded to GitHub from the handler. */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UploadUrlRequest"];
                };
            };
            responses: {
                /** @description Upload url generated successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UploadUrlResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GenericError"];
                    };
                };
                /** @description Unauthenticated - Missing or invalid authentication token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Forbidden - Not allowed to upload a level here */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/levels/{levelId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Returns the level information for a given level ID. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The internal Github id of the level, which never changes, even if the repo is transferred. */
                    levelId: components["parameters"]["LevelId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A level object */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Level"];
                    };
                };
                /** @description Level not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/levels/{levelId}/exits/{exitName}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Returns the exit for a given level ID and exit name. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The internal Github id of the level, which never changes, even if the repo is transferred. */
                    levelId: components["parameters"]["LevelId"];
                    /** @description The name of the exit */
                    exitName: components["parameters"]["ExitName"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description An exit object */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Exit"];
                    };
                };
                /** @description Forbidden - Player does not have access to this resource */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Exit not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/players/{playerId}/markers/{markerId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Updates the marker information for a given player ID and marker ID. */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The ID of the player */
                    playerId: components["parameters"]["PlayerId"];
                    /** @description The ID of the marker */
                    markerId: components["parameters"]["MarkerId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Marker updated successfully */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Forbidden - Player does not have access to this resource */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Marker not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        /** Returns the marker information for a given player ID and marker ID. */
        head: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The ID of the player */
                    playerId: components["parameters"]["PlayerId"];
                    /** @description The ID of the marker */
                    markerId: components["parameters"]["MarkerId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Marker exists */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Forbidden - Player does not have access to this resource */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Marker not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        GenericError: {
            /** @description A description of the error */
            error: string;
        };
        ZodIssue: {
            /** @example too_small */
            code?: string;
            message: string;
            path: (string | number)[];
        };
        ZodIssuesError: {
            issues?: components["schemas"]["ZodIssue"][];
        };
        CreateLevel: {
            name: string;
            credits: components["schemas"]["LevelCredit"][];
            /**
             * Format: uri
             * @default https://github.com/user/repo
             */
            source: string;
        };
        LevelCredit: {
            role: string;
            name: string;
            /**
             * Format: uri
             * @default https://yourwebsite.com
             */
            url: string;
        };
        Level: {
            id: string;
            commit: string;
            /** @description The GitHub repository (owner/repo) where the level is stored */
            repo: string;
            /** @description The name of the level */
            name: string;
            /** @description The URL path to the level */
            path: string;
            entrances: string[];
            /** @description The first unattached entrance to the level */
            mainEntrance?: string;
            exits: string[];
        };
        Player: {
            id: string;
            name: string;
        };
        Item: {
            id: string;
            name: string;
            description: string;
        };
        JobStatus: {
            /**
             * @description The status of the upload job
             * @enum {string}
             */
            status: "pending" | "completed" | "failed";
            /** @description The unix timestamp when the job started */
            startTime: number;
            /** @description The unix timestamp when the job was last updated, if applicable */
            lastUpdateTime: number;
            /** @description The error, if status is failed */
            errorMessage?: string;
        };
        JobStatusResponse: {
            job: components["schemas"]["JobStatus"];
            level?: components["schemas"]["Level"];
        };
        UploadUrlResponse: {
            /** @description The ID of the upload job */
            jobId: string;
            /**
             * Format: uri
             * @description The pre-signed URL for uploading the level
             */
            url: string;
            /** @description The expiration time of the pre-signed URL */
            expiresIn: number;
            /** @description The maximum size allowed for the upload in bytes */
            maxSize: number;
            /** @description Additional fields required for the upload */
            fields: {
                [key: string]: string;
            };
        };
        UploadUrlRequest: {
            /** @description GitHub token from workflow job. */
            githubToken: string;
        };
        Exit: {
            level: components["schemas"]["Level"];
            /** @description The entrance to the level that this exit leads to */
            entrance: string;
        };
    };
    responses: never;
    parameters: {
        /** @description The ID of the player */
        PlayerId: string;
        /** @description The ID of the marker */
        MarkerId: string;
        /** @description The internal Github id of the level, which never changes, even if the repo is transferred. */
        LevelId: string;
        /** @description The ID of the publish job */
        JobId: string;
        /** @description The name of the exit */
        ExitName: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
