name: Template Publish
on:
  push:

jobs:
  license-check:
    if: github.repository == 'amoffat/getlost-level-template'
    name: Check Licenses
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        working-directory: .internal

      - name: Check licenses
        run: |
          pnpm run license-check
        working-directory: .internal

  notify:
    if: github.repository == 'amoffat/getlost-level-template' && github.event_name == 'push' && github.ref == 'refs/heads/main'
    name: Send Discord Notification
    runs-on: ubuntu-latest
    needs: license-check
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set version
        id: set-version
        run: |
          version=$(jq -r .version .internal/package.json | sed 's/\+.*//')
          echo "version=$version" >> $GITHUB_ENV

      - name: Send Discord Notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          VERSION: ${{ env.version }}
        run: python3 .internal/scripts/discord.py
